# Generated by Django 2.0.4 on 2018-04-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('decripcion', models.TextField()),
                ('imagen', models.URLField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
