# Generated by Django 2.0.4 on 2018-04-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='tipo',
            field=models.CharField(choices=[('HEROE', 'HEROE'), ('VILLANO', 'VILLANO')], default='HEROE', max_length=20),
        ),
    ]
